development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudhub_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudhub_production
